version: '3.8'
services:
  discovery-service:
    container_name: discovery-service
    image: ouday2025/discovery-service:latest
    build:
      context: ./eureka
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    hostname: eureka
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app-network

  mysql-container:
    container_name: mysql-container-offre
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=your_secure_password
#      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  keycloak:
    container_name: microservice-keycloak-1
    build:
      context: ./keycloak
      dockerfile: Dockerfile
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - DB_VENDOR=mysql
      - DB_ADDR=mysql-container-offre
      - DB_PORT=3306
      - DB_DATABASE=KeycloakDB
      - DB_USER=root
      - DB_PASSWORD=
      - KEYCLOAK_JDBC_PARAMS=useSSL=false&allowPublicKeyRetrieval=true
      - KC_HOSTNAME_STRICT=false
      - KEYCLOAK_FRONTEND_URL=http://keycloak:8080
    ports:
      - "8180:8080"
    command: start-dev --import-realm
    depends_on:
      mysql-container:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/realms/myrealm/.well-known/openid-configuration" ]
      interval: 10s
      timeout: 5s
      retries: 20
    networks:
      - app-network
    volumes:
      - ./keycloak/export:/opt/keycloak/data/import

  gateway-service:
    container_name: gateway-service
    image: ouday2025/gateway-service:latest
    build:
      context: ./Gateway
      dockerfile: Dockerfile
    ports:
      - "8093:8093"
    hostname: gateway
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_PROFILES_ACTIVE=default
    depends_on:
      discovery-service:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    networks:
      - app-network

  offre-promotion-service:
    container_name: offre-promotion-service
    image: ouday2025/offre-promotion-service:latest
    build:
      context: ./offre_promotion
      dockerfile: Dockerfile
    ports:
      - "8085:8088"
    hostname: offre-promotion
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-container-offre:3306/OffrePromotion?autoReconnect=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=your_secure_password
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    depends_on:
      discovery-service:
        condition: service_healthy
      mysql-container:
        condition: service_healthy
      keycloak:
          condition: service_healthy
    networks:
      - app-network
  stock-service:
    build: ./GESTIONSTOCK
    image: halimtrabelsi/stock-service:latest
    container_name: stock-service
    ports:
      - "8089:8089"
    hostname: stock-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-container-offre:3306/OffrePromotion?autoReconnect=true&useSSL=false
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    depends_on:
      discovery-service:
        condition: service_healthy
      mysql-container:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    networks:
      - app-network

  reclamation:
    build:
      context: ./Reclamation
    ports:
      - "8090:8090"
    image: "ouday2025/reclamation"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-container-offre:3306/OffrePromotion?autoReconnect=true&useSSL=false
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    depends_on:
      discovery-service:
        condition: service_healthy
      mysql-container:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    networks:
      - app-network
  produit-service:
    container_name: produit-service
    image: ouday2025/produit-service:latest
    build:
      context: ./backproduit
      dockerfile: Dockerfile
    ports:
      - "8091:8091"
    hostname: backproduit
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-container-offre:3306/OffrePromotion?autoReconnect=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=your_secure_password
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    depends_on:
      discovery-service:
        condition: service_healthy
      mysql-container:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    networks:
      - app-network
  blog-service:
    container_name: blog-service
    image: ouday2025/blog-service:latest
    build:
      context: ./Blog
      dockerfile: Dockerfile
    ports:
      - "8092:8092"
    hostname: Blog
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MySQL
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.h2.Driver
      - SPRING_H2_CONSOLE_ENABLED=true
    depends_on:
      discovery-service:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge